{% set name = "lume-impact" %}
{% set version = "0.12.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: e0097f8efd62abb435ef8e03d6130d859220f3200d034b25b11d1ebb9f4979cb

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - bokeh
    - distgen
    - impact-t >=3
    - impact-z >=2.7.2
    - lume-base
    - matplotlib-base
    - numpy
    - openpmd-beamphysics >=0.14.0
    - polars
    - prettytable
    - psutil
    - pydantic
    - pydantic-settings
    - rich
    - tqdm
    - typing-extensions

test:
  source_files:
    - docs/examples/
  imports:
    - impact
    - impact.z
  requires:
    - pytest
    - pytest-cov
    - bmad >=20260223.1
    - pytao >=1.0.0
    - python {{ python_min }}
  commands:
    - python -m pytest --pyargs impact -k "not test_bmad and not test_output and not test_distgen_model"

about:
  home: https://github.com/lume-science/lume-impact
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LUME Python wrapper for Impact-T
  description: LUME Python wrapper for Impact-T

extra:
  recipe-maintainers:
    - ChristopherMayes
    - ken-lauer
    - tangkong
